#!/usr/bin/env node
/**
 * Vendor the app's icon glyphs (STC-456).
 *
 *   node scripts/vendor-icons.mjs
 *
 * Material Symbols, Outlined, weight 300 (Patrick, 2026-09-28), from the npm
 * package `@material-symbols/svg-300` at a PINNED version, Apache-2.0. This
 * packs that exact version into a temp dir, keeps only each glyph's path `d`
 * (their viewBox is `0 -960 960 960`), and writes:
 *
 *   app/src/icons.ts           — GENERATED; edit only by re-running this
 *   app/src/icons.LICENSE.txt  — the package's own LICENSE, verbatim
 *
 * Both are committed. The build never fetches anything; this script is how a
 * glyph gets added or the version moved, and it is the only way.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PKG = "@material-symbols/svg-300";
const VERSION = "0.47.5";
/** Our glyph name -> the Material Symbol it is drawn with. */
const MAP = {
  "expand": "open_in_full",
  "crop": "crop",
  "settings": "tune",
  "mic": "mic",
  "mic-off": "mic_off",
  "camera": "videocam",
  "camera-off": "videocam_off",
  "system-audio": "laptop_mac",
  "command": "keyboard_command_key",
  "click": "ads_click",
  "record": "radio_button_checked",
  "return": "keyboard_return",
  "caret": "keyboard_arrow_down",
  "check": "check",
};

const root = new URL("..", import.meta.url).pathname;
const tmp = mkdtempSync(join(tmpdir(), "vendor-icons-"));
try {
  const out = execFileSync("npm", ["pack", `${PKG}@${VERSION}`, "--silent"], { cwd: tmp, encoding: "utf8" });
  const tgz = out.trim().split("\n").pop();
  const members = ["package/LICENSE", ...Object.values(MAP).map((n) => `package/outlined/${n}.svg`)];
  execFileSync("tar", ["-xzf", tgz, ...members], { cwd: tmp });

  const paths = {};
  for (const [glyph, symbol] of Object.entries(MAP)) {
    const svg = readFileSync(join(tmp, "package/outlined", `${symbol}.svg`), "utf8");
    if (!svg.includes('viewBox="0 -960 960 960"')) throw new Error(`${symbol}: unexpected viewBox`);
    const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
    if (ds.length === 0) throw new Error(`${symbol}: no <path d>`);
    paths[glyph] = ds.join("");
  }

  const glyphs = Object.keys(MAP);
  const ts = `// GENERATED by scripts/vendor-icons.mjs — do not edit; re-run the script.
//
// Material Symbols, Outlined, weight 300: ${PKG}@${VERSION}, Apache-2.0
// (the licence is app/src/icons.LICENSE.txt). One path per glyph, viewBox
// 0 -960 960 960. Node-free, so every renderer can import it. Material
// Symbols are FILLED outlines: draw them with \`fill: currentColor\`, never a
// stroke.

export type Glyph =
${glyphs.map((g) => `  | ${JSON.stringify(g)}`).join("\n")};

/** Which Material Symbol each glyph is, for anyone checking the mapping. */
export const SYMBOL: Readonly<Record<Glyph, string>> = {
${glyphs.map((g) => `  ${JSON.stringify(g)}: ${JSON.stringify(MAP[g])},`).join("\n")}
};

const PATHS: Readonly<Record<Glyph, string>> = {
${glyphs.map((g) => `  ${JSON.stringify(g)}: ${JSON.stringify(paths[g])},`).join("\n")}
};

/** One glyph as an inline SVG, filled with currentColor; CSS sizes it. */
export function iconSvg(g: Glyph, cls = ""): string {
  return \`<svg class="\${cls}" viewBox="0 -960 960 960" aria-hidden="true"><path d="\${PATHS[g]}"/></svg>\`;
}
`;
  writeFileSync(join(root, "app/src/icons.ts"), ts);
  writeFileSync(join(root, "app/src/icons.LICENSE.txt"), readFileSync(join(tmp, "package/LICENSE"), "utf8"));
  console.log(`wrote app/src/icons.ts (${glyphs.length} glyphs from ${PKG}@${VERSION})`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
